vars:
  registry: docker-registry.dun.fh
  service_name: vaultix

tasks:
  build:
    - cmd: docker build --force-rm -t <%=registry%>/findmypast/<%=service_name%>:<%=version%> .

  push:
    - cmd: docker push <%=registry%>/findmypast/<%=service_name%>:<%=version%>

  # Run unit tests inside a container
  test:
    - cmd: docker run --name vaultix-test-runner --rm <%=registry%>/findmypast/<%=service_name%>:<%=version%> mix test

  # Publish to Hex Repository
  publish:
    - cmd: docker pull <%=registry%>/findmypast/<%=service_name%>:<%=version%>
    - cmd: docker run -e HEX_USER -e HEX_PASSWORD --name vaultix-publisher --rm <%=registry%>/findmypast/<%=service_name%>:<%=version%> ./publish.sh
      environment:
        - HEX_USER=<%=user%>
        - HEX_PASSWORD=<%=password%>
        - LOCAL_PWD=<%=password%>
